name: Build & Deploy to Production

on:
  push:
    branches:
      - production

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        run: |
          git fetch --depth=1 origin ${{ github.sha }}
          git reset --hard ${{ github.sha }}

      - name: Clean previous build
        run: rm -rf dist/

      - name: Install dependencies
        run: npm i

      - name: Build project
        run: npm run build

      - name: Clean production folder
        run: rm -rf /var/www/portfolio_prod/*

      - name: Deploy new build
        run: cp -r dist/* /var/www/portfolio_prod/
